global using Microsoft.AspNetCore.Mvc;
global using System.Text.Json.Serialization;
global using CentavoControl.Infrastructure;
global using Microsoft.AspNetCore.Server.Kestrel.Core;
global using CentavoControl.Configurations;
global using Controller = Microsoft.AspNetCore.Mvc.Controller;
global using Asp.Versioning;
global using CentavoControl.Application;
global using Microsoft.AspNetCore.Http.Extensions;
global using CentavoControl.Application.Commands.Category;
global using CentavoControl.Application.Queries.Category;
global using CentavoControl.Application.Commands.Account;
global using CentavoControl.Application.Queries.Account;
global using CentavoControl.Application.Validators.Account.Commands;
global using CentavoControl.Domain.Interfaces.Repositories;